module.exports = {
  extends: ['eslint:recommended', 'plugin:eslint-comments/recommended', 'prettier'],
  plugins: ['eslint-comments', 'prettier'],
  env: {
    browser: true
  },
  parserOptions: {
    ecmaVersion: 5
  },
  rules: {
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'consistent-return': 'error',
    'default-case': ['error', { commentPattern: '^skip\\sdefault' }],
    'dot-notation': 'error',
    eqeqeq: 'error',
    'guard-for-in': 'error',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-caller': 'error',
    'no-console': ['error', { allow: ['info', 'warn', 'error'] }],
    'no-else-return': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-label': 'error',
    'no-mixed-requires': ['error', { grouping: true, allowCall: true }],
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-require': 'error',
    'no-new-wrappers': 'error',
    'no-octal-escape': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-restricted-syntax': ['error', 'WithStatement'],
    'no-return-assign': ['error', 'always'],
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow-restricted-names': 'error',
    'no-throw-literal': 'error',
    'no-undef-init': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    'no-use-before-define': ['error', 'nofunc'],
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'one-var': ['error', 'never'],
    'operator-assignment': ['error', 'always'],
    'prefer-numeric-literals': 'error',
    radix: 'error',
    yoda: 'error',

    'prettier/prettier': 'error'
  }
};
