module.exports = {
  extends: ['prettier'],
  plugins: ['prettier'],
  parser: '@babel/eslint-parser',
  env: {
    node: true,
  },
  parserOptions: {
    ecmaVersion: 'latest',
  },
  rules: {
    'class-methods-use-this': 'error',
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'logical-assignment-operators': ['error', 'always'],
    'no-constructor-return': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-promise-executor-return': 'error',
    'no-return-await': 'error',
    'no-template-curly-in-string': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-private-class-members': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'error',
    'prefer-exponentiation-operator': 'error',
    'prefer-object-has-own': 'error',
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-atomic-updates': 'error',
    'symbol-description': 'error',

    'prettier/prettier': 'error',
  },
}
